### ISSUE TITLE
mihdan_clockwork()->notice( 'Усё пропало, шеф!' ) - это не WP way

### ISSUE THREAD

**Issue by aiiddqd** [mihdan/mihdan-clockwork#1]
WP way =
`do_action('mc', 'Усё пропало, шеф!');`

не будет фаталить если плагин отключить.

mihdan_clockwork()->notice( 'Усё пропало, шеф!' ) - что то с плагином и получаем фатал.

примеры WP way:
https://github.com/uptimizt/logger-u7
https://github.com/johnbillion/query-monitor#logging

**Comment by mihdan** [comment]
Спасибо за дельное замечание, ушел переписывать код)

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-clockwork/commit/01bbffd4dcf748550672360f2fac111f871ca899
